{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6ab49a34-b45f-4e92-9bd5-940159c0487b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# %% [markdown]\n",
    "# # 🧭 Search Algorithm Visualizer\n",
    "# ## Interactive Jupyter Notebook Version\n",
    "# \n",
    "# This notebook provides a complete implementation of search algorithm visualization.\n",
    "# Run all cells to launch the interactive app.\n",
    "\n",
    "# %% [markdown]\n",
    "# ## Installation\n",
    "\n",
    "# %%\n",
    "import subprocess\n",
    "import sys\n",
    "\n",
    "def install_packages():\n",
    "    \"\"\"Install required packages\"\"\"\n",
    "    packages = ['streamlit', 'numpy', 'matplotlib', 'pandas']\n",
    "    for package in packages:\n",
    "        subprocess.check_call([sys.executable, \"-m\", \"pip\", \"install\", \"-q\", package])\n",
    "        print(f\"✅ Installed {package}\")\n",
    "\n",
    "# Uncomment the line below to install packages\n",
    "# install_packages()\n",
    "\n",
    "# %% [markdown]\n",
    "# ## Complete Implementation\n",
    "\n",
    "# %%\n",
    "import streamlit as st\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.patches as patches\n",
    "from matplotlib.colors import ListedColormap\n",
    "import time\n",
    "from collections import deque\n",
    "import heapq\n",
    "import random\n",
    "from typing import List, Tuple, Optional, Dict, Set\n",
    "import copy\n",
    "import pandas as pd\n",
    "\n",
    "# %% [markdown]\n",
    "# ### Search Algorithm Class\n",
    "\n",
    "# %%\n",
    "class SearchVisualizer:\n",
    "    \"\"\"Core search algorithms and grid management\"\"\"\n",
    "    \n",
    "    def __init__(self, rows=20, cols=30):\n",
    "        self.rows = rows\n",
    "        self.cols = cols\n",
    "        self.grid = None\n",
    "        self.start = None\n",
    "        self.end = None\n",
    "        self.reset_grid()\n",
    "    \n",
    "    def reset_grid(self):\n",
    "        \"\"\"Initialize empty grid\"\"\"\n",
    "        self.grid = np.zeros((self.rows, self.cols), dtype=int)\n",
    "        self.start = (2, 2)\n",
    "        self.end = (self.rows-3, self.cols-3)\n",
    "        self.grid[self.start] = 2\n",
    "        self.grid[self.end] = 3\n",
    "    \n",
    "    def toggle_wall(self, row, col):\n",
    "        if (row, col) == self.start or (row, col) == self.end:\n",
    "            return\n",
    "        self.grid[row, col] = 1 if self.grid[row, col] == 0 else 0\n",
    "    \n",
    "    def set_start(self, row, col):\n",
    "        if self.grid[row, col] == 1:\n",
    "            return\n",
    "        if self.start:\n",
    "            self.grid[self.start] = 0\n",
    "        self.start = (row, col)\n",
    "        self.grid[row, col] = 2\n",
    "    \n",
    "    def set_end(self, row, col):\n",
    "        if self.grid[row, col] == 1:\n",
    "            return\n",
    "        if self.end:\n",
    "            self.grid[self.end] = 0\n",
    "        self.end = (row, col)\n",
    "        self.grid[row, col] = 3\n",
    "    \n",
    "    def get_neighbors(self, pos):\n",
    "        r, c = pos\n",
    "        neighbors = []\n",
    "        for dr, dc in [(-1,0), (1,0), (0,-1), (0,1)]:\n",
    "            nr, nc = r + dr, c + dc\n",
    "            if 0 <= nr < self.rows and 0 <= nc < self.cols:\n",
    "                if self.grid[nr, nc] != 1:\n",
    "                    neighbors.append((nr, nc))\n",
    "        return neighbors\n",
    "    \n",
    "    def heuristic(self, pos):\n",
    "        return abs(pos[0] - self.end[0]) + abs(pos[1] - self.end[1])\n",
    "    \n",
    "    def bfs(self):\n",
    "        queue = deque([self.start])\n",
    "        visited = {self.start: None}\n",
    "        order = []\n",
    "        while queue:\n",
    "            current = queue.popleft()\n",
    "            order.append(current)\n",
    "            if current == self.end:\n",
    "                break\n",
    "            for neighbor in self.get_neighbors(current):\n",
    "                if neighbor not in visited:\n",
    "                    visited[neighbor] = current\n",
    "                    queue.append(neighbor)\n",
    "        path = self.reconstruct_path(visited)\n",
    "        return order, path, visited\n",
    "    \n",
    "    def dfs(self):\n",
    "        stack = [self.start]\n",
    "        visited = {self.start: None}\n",
    "        order = []\n",
    "        while stack:\n",
    "            current = stack.pop()\n",
    "            order.append(current)\n",
    "            if current == self.end:\n",
    "                break\n",
    "            for neighbor in self.get_neighbors(current):\n",
    "                if neighbor not in visited:\n",
    "                    visited[neighbor] = current\n",
    "                    stack.append(neighbor)\n",
    "        path = self.reconstruct_path(visited)\n",
    "        return order, path, visited\n",
    "    \n",
    "    def ucs(self):\n",
    "        pq = [(0, self.start)]\n",
    "        visited = {self.start: (0, None)}\n",
    "        order = []\n",
    "        while pq:\n",
    "            cost, current = heapq.heappop(pq)\n",
    "            order.append(current)\n",
    "            if current == self.end:\n",
    "                break\n",
    "            for neighbor in self.get_neighbors(current):\n",
    "                new_cost = cost + 1\n",
    "                if neighbor not in visited or new_cost < visited[neighbor][0]:\n",
    "                    visited[neighbor] = (new_cost, current)\n",
    "                    heapq.heappush(pq, (new_cost, neighbor))\n",
    "        path = []\n",
    "        if self.end in visited:\n",
    "            current = self.end\n",
    "            while current:\n",
    "                path.append(current)\n",
    "                current = visited[current][1]\n",
    "            path.reverse()\n",
    "        return order, path, visited\n",
    "    \n",
    "    def greedy(self):\n",
    "        pq = [(self.heuristic(self.start), self.start)]\n",
    "        visited = {self.start: None}\n",
    "        order = []\n",
    "        while pq:\n",
    "            _, current = heapq.heappop(pq)\n",
    "            order.append(current)\n",
    "            if current == self.end:\n",
    "                break\n",
    "            for neighbor in self.get_neighbors(current):\n",
    "                if neighbor not in visited:\n",
    "                    visited[neighbor] = current\n",
    "                    heapq.heappush(pq, (self.heuristic(neighbor), neighbor))\n",
    "        path = self.reconstruct_path(visited)\n",
    "        return order, path, visited\n",
    "    \n",
    "    def astar(self):\n",
    "        pq = [(self.heuristic(self.start), 0, self.start)]\n",
    "        visited = {self.start: (0, None)}\n",
    "        order = []\n",
    "        while pq:\n",
    "            f, g, current = heapq.heappop(pq)\n",
    "            order.append(current)\n",
    "            if current == self.end:\n",
    "                break\n",
    "            for neighbor in self.get_neighbors(current):\n",
    "                new_g = g + 1\n",
    "                if neighbor not in visited or new_g < visited[neighbor][0]:\n",
    "                    visited[neighbor] = (new_g, current)\n",
    "                    heapq.heappush(pq, (new_g + self.heuristic(neighbor), new_g, neighbor))\n",
    "        path = []\n",
    "        if self.end in visited:\n",
    "            current = self.end\n",
    "            while current:\n",
    "                path.append(current)\n",
    "                current = visited[current][1]\n",
    "            path.reverse()\n",
    "        return order, path, visited\n",
    "    \n",
    "    def reconstruct_path(self, visited):\n",
    "        path = []\n",
    "        if self.end in visited:\n",
    "            current = self.end\n",
    "            while current:\n",
    "                path.append(current)\n",
    "                current = visited[current]\n",
    "            path.reverse()\n",
    "        return path\n",
    "    \n",
    "    def run_algorithm(self, algo_name):\n",
    "        algorithms = {\n",
    "            'BFS': self.bfs,\n",
    "            'DFS': self.dfs,\n",
    "            'UCS': self.ucs,\n",
    "            'Greedy': self.greedy,\n",
    "            'A*': self.astar\n",
    "        }\n",
    "        if algo_name not in algorithms:\n",
    "            return None\n",
    "        start_time = time.time()\n",
    "        order, path, visited = algorithms[algo_name]()\n",
    "        elapsed = (time.time() - start_time) * 1000\n",
    "        return {\n",
    "            'order': order,\n",
    "            'path': path,\n",
    "            'visited': visited,\n",
    "            'nodes_explored': len(order) if order else 0,\n",
    "            'path_length': len(path) - 1 if path else 0,\n",
    "            'path_cost': len(path) - 1 if path else 0,\n",
    "            'time': elapsed,\n",
    "            'found': path is not None and len(path) > 0\n",
    "        }\n",
    "\n",
    "# %% [markdown]\n",
    "# ### Streamlit App\n",
    "\n",
    "# %%\n",
    "def main():\n",
    "    st.set_page_config(page_title=\"Search Visualizer\", page_icon=\"🧭\", layout=\"wide\")\n",
    "    \n",
    "    st.title(\"🧭 Search Algorithm Visualizer\")\n",
    "    st.markdown(\"### BFS · DFS · UCS · Greedy · A*\")\n",
    "    st.markdown(\"---\")\n",
    "    \n",
    "    if 'visualizer' not in st.session_state:\n",
    "        st.session_state.visualizer = SearchVisualizer(rows=20, cols=30)\n",
    "        st.session_state.results = {}\n",
    "        st.session_state.last_result = None\n",
    "        st.session_state.current_algo = None\n",
    "    \n",
    "    visualizer = st.session_state.visualizer\n",
    "    \n",
    "    # Sidebar\n",
    "    with st.sidebar:\n",
    "        st.header(\"🎮 Controls\")\n",
    "        algorithm = st.selectbox(\"Algorithm\", [\"BFS\", \"DFS\", \"UCS\", \"Greedy\", \"A*\"], index=4)\n",
    "        \n",
    "        col1, col2 = st.columns(2)\n",
    "        with col1:\n",
    "            if st.button(\"▶️ Visualize\", use_container_width=True):\n",
    "                with st.spinner(f\"Running {algorithm}...\"):\n",
    "                    result = visualizer.run_algorithm(algorithm)\n",
    "                    if result:\n",
    "                        st.session_state.last_result = result\n",
    "                        st.session_state.current_algo = algorithm\n",
    "                        st.session_state.results[algorithm] = result\n",
    "                        st.rerun()\n",
    "        with col2:\n",
    "            if st.button(\"📊 Compare All\", use_container_width=True):\n",
    "                with st.spinner(\"Running all algorithms...\"):\n",
    "                    for algo in [\"BFS\", \"DFS\", \"UCS\", \"Greedy\", \"A*\"]:\n",
    "                        result = visualizer.run_algorithm(algo)\n",
    "                        if result:\n",
    "                            st.session_state.results[algo] = result\n",
    "                    st.session_state.last_result = None\n",
    "                    st.rerun()\n",
    "        \n",
    "        st.markdown(\"---\")\n",
    "        st.subheader(\"🗺️ Grid\")\n",
    "        if st.button(\"🧹 Clear Paths\", use_container_width=True):\n",
    "            st.session_state.last_result = None\n",
    "            st.session_state.results = {}\n",
    "            st.rerun()\n",
    "        if st.button(\"🎲 Random Walls\", use_container_width=True):\n",
    "            for r in range(visualizer.rows):\n",
    "                for c in range(visualizer.cols):\n",
    "                    if (r, c) != visualizer.start and (r, c) != visualizer.end:\n",
    "                        if random.random() < 0.25:\n",
    "                            visualizer.toggle_wall(r, c)\n",
    "            st.session_state.last_result = None\n",
    "            st.session_state.results = {}\n",
    "            st.rerun()\n",
    "        if st.button(\"🗑️ Reset Grid\", use_container_width=True):\n",
    "            visualizer.reset_grid()\n",
    "            st.session_state.last_result = None\n",
    "            st.session_state.results = {}\n",
    "            st.rerun()\n",
    "    \n",
    "    # Main content\n",
    "    col1, col2 = st.columns([2, 1])\n",
    "    \n",
    "    with col1:\n",
    "        st.subheader(\"🗺️ Interactive Grid\")\n",
    "        click_mode = st.radio(\"Click Mode\", [\"Wall\", \"Start\", \"Goal\"], horizontal=True)\n",
    "        \n",
    "        for r in range(visualizer.rows):\n",
    "            cols = st.columns(visualizer.cols)\n",
    "            for c in range(visualizer.cols):\n",
    "                cell_value = visualizer.grid[r, c]\n",
    "                if (r, c) == visualizer.start:\n",
    "                    bg, label = \"#22c55e\", \"S\"\n",
    "                elif (r, c) == visualizer.end:\n",
    "                    bg, label = \"#ef4444\", \"G\"\n",
    "                elif cell_value == 1:\n",
    "                    bg, label = \"#4a4a4a\", \"■\"\n",
    "                else:\n",
    "                    bg, label = \"#f0f0f0\", \" \"\n",
    "                \n",
    "                is_explored = False\n",
    "                is_path = False\n",
    "                if st.session_state.last_result:\n",
    "                    order = st.session_state.last_result.get('order', [])\n",
    "                    path = st.session_state.last_result.get('path', [])\n",
    "                    if (r, c) in order and (r, c) != visualizer.start and (r, c) != visualizer.end:\n",
    "                        is_explored = True\n",
    "                        if (r, c) in path:\n",
    "                            is_path = True\n",
    "                \n",
    "                style = f\"\"\"\n",
    "                    background-color: {bg};\n",
    "                    color: {'black' if bg == '#f0f0f0' else 'white'};\n",
    "                    border: 1px solid #ddd;\n",
    "                    padding: 8px 0;\n",
    "                    text-align: center;\n",
    "                    font-weight: bold;\n",
    "                    font-size: 16px;\n",
    "                    cursor: pointer;\n",
    "                    transition: all 0.2s;\n",
    "                \"\"\"\n",
    "                if is_explored and not is_path:\n",
    "                    style += \" background-color: #87CEEB; opacity: 0.6;\"\n",
    "                if is_path:\n",
    "                    style += \" background-color: #FFD700; border: 2px solid #FFA500;\"\n",
    "                \n",
    "                if cols[c].button(label, key=f\"c_{r}_{c}\", use_container_width=True):\n",
    "                    if click_mode == \"Wall\":\n",
    "                        if (r, c) != visualizer.start and (r, c) != visualizer.end:\n",
    "                            visualizer.toggle_wall(r, c)\n",
    "                            st.session_state.last_result = None\n",
    "                            st.session_state.results = {}\n",
    "                            st.rerun()\n",
    "                    elif click_mode == \"Start\":\n",
    "                        if cell_value != 1:\n",
    "                            visualizer.set_start(r, c)\n",
    "                            st.session_state.last_result = None\n",
    "                            st.session_state.results = {}\n",
    "                            st.rerun()\n",
    "                    elif click_mode == \"Goal\":\n",
    "                        if cell_value != 1:\n",
    "                            visualizer.set_end(r, c)\n",
    "                            st.session_state.last_result = None\n",
    "                            st.session_state.results = {}\n",
    "                            st.rerun()\n",
    "    \n",
    "    with col2:\n",
    "        st.subheader(\"📊 Results\")\n",
    "        \n",
    "        if st.session_state.last_result:\n",
    "            result = st.session_state.last_result\n",
    "            algo = st.session_state.current_algo\n",
    "            st.markdown(f\"**Algorithm:** {algo}\")\n",
    "            col_a, col_b = st.columns(2)\n",
    "            with col_a:\n",
    "                st.metric(\"Path Found\", \"✅\" if result['found'] else \"❌\")\n",
    "                st.metric(\"Path Length\", result['path_length'] if result['found'] else \"—\")\n",
    "            with col_b:\n",
    "                st.metric(\"Nodes Explored\", result['nodes_explored'])\n",
    "                st.metric(\"Time\", f\"{result['time']:.1f}ms\")\n",
    "        \n",
    "        if st.session_state.results:\n",
    "            st.subheader(\"🏆 Comparison\")\n",
    "            data = []\n",
    "            for algo, result in st.session_state.results.items():\n",
    "                data.append({\n",
    "                    'Algorithm': algo,\n",
    "                    'Found': '✅' if result['found'] else '❌',\n",
    "                    'Path Length': result['path_length'] if result['found'] else '—',\n",
    "                    'Nodes Explored': result['nodes_explored'],\n",
    "                    'Time (ms)': f\"{result['time']:.1f}\"\n",
    "                })\n",
    "            df = pd.DataFrame(data)\n",
    "            st.dataframe(df, use_container_width=True)\n",
    "            \n",
    "            if data:\n",
    "                best = min([d for d in data if d['Found'] == '✅'], \n",
    "                          key=lambda x: x['Path Length'] if isinstance(x['Path Length'], int) else float('inf'))\n",
    "                if best['Found'] == '✅':\n",
    "                    st.success(f\"🏆 Best: {best['Algorithm']} (path length {best['Path Length']})\")\n",
    "                else:\n",
    "                    st.warning(\"No algorithm found a path\")\n",
    "        \n",
    "        st.subheader(\"📈 Stats\")\n",
    "        st.markdown(f\"\"\"\n",
    "        - Grid: {visualizer.rows}×{visualizer.cols}\n",
    "        - Walls: {np.sum(visualizer.grid == 1)}\n",
    "        - Start: {visualizer.start}\n",
    "        - Goal: {visualizer.end}\n",
    "        \"\"\")\n",
    "\n",
    "# %% [markdown]\n",
    "# ## Run the App\n",
    "\n",
    "# %%\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n",
    "\n",
    "# %% [markdown]\n",
    "# ## Alternative: Run from Terminal\n",
    "# \n",
    "# You can also save the code as `visualizer.py` and run:\n",
    "# ```\n",
    "# streamlit run visualizer.py\n",
    "# ```\n",
    "\n",
    "# %% [markdown]\n",
    "# ## Usage Instructions\n",
    "# \n",
    "# 1. **Click on grid cells** to toggle walls (gray cells)\n",
    "# 2. **Use radio buttons** to switch between Wall, Start, and Goal modes\n",
    "# 3. **Select an algorithm** from the sidebar dropdown\n",
    "# 4. **Click \"Visualize\"** to run the selected algorithm\n",
    "# 5. **Click \"Compare All\"** to run all algorithms and see results\n",
    "# 6. **Use grid controls** to clear paths, add random walls, or reset the grid\n",
    "# \n",
    "# ## Features\n",
    "# \n",
    "# - ✅ 5 search algorithms: BFS, DFS, UCS, Greedy, A*\n",
    "# - ✅ Interactive grid editing with clickable cells\n",
    "# - ✅ Visual feedback showing explored nodes (blue) and path (yellow)\n",
    "# - ✅ Real-time stats for each algorithm run\n",
    "# - ✅ Side-by-side comparison table\n",
    "# - ✅ Random wall generation\n",
    "# - ✅ Path and grid clearing"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
